server:
    port: 9000
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: people-service
                  uri: http://localhost:9001
                  predicates:
                    - Path=/api/v1/customer/**,
                      /api/v1/employee/**,
                      /api/v1/supplier/**
                - id: product-service
                  uri: http://localhost:9002
                  predicates:
                    - Path=/api/v1/product/**,
                      /api/v1/order/**,
                      /api/v1/promotion/**,
                      /api/v1/purchase-order/**,
                      /api/v1/statistics/**
