eureka:
  client:
    service-url:git
      default-zone: http://localhost:8761/eureka
server:
  port: 9002
spring:
  application:
    name: product-service
  datasource:
    password: 01268797378Zx
    url: jdbc:mysql://localhost:3306/tttn-product
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
cloudinary:
  cloud_name: djvdipdcc
  api_key: 165468179911166
  api_secret: CZVlFL4xfrCrKjNAUqeNVH4sSlE
