eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9001
spring:
  application:
    name: people-service
  datasource:
    password: 01268797378Zx
    url: jdbc:mysql://localhost:3306/tttn-people
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    password: wudb sqhe xkvz znaj
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ahihi1230zx@gmail.com
security:
  jwt:
    secret-key: "A2C7EA17F982FC8BA215538981A92"